### ISSUE TITLE
Critical Error with "AddressService Error: No Memory Scanner"

### ISSUE THREAD

**Issue by Ricky7945** [imchillin/Anamnesis#1100]
**Describe the bug**

Anamnesis had been worked until I downloaded and ran the [2022-05-31.zip].
Even if I downloaded NET.6.05 and restart my PC, Anamnesis still fails to open.

Critical Error with "AddressService Error: No Memory Scanner"
No memory scanner

[Exception] AddressService Error: No memory scanner
[Exception] No memory scanner
 at Anamnesis.Core.Memory.AddressService.GetAddressFromSignature(String name, String signature, Int32 offset, Action '1 callback)
 at Anamnesis.Core.Memory.AddressService.Scan()
 at Anamnesis.Core.Memory.AddressService.Initialize()
 at Anamnesis.Services.ServiceManager.InitializeService(IService service)
 at Anamnesis.Services.ServiceManager.Add[T]()

**Comment by Yuki-Codes** [comment]
Can you please upload a log file?

**Comment by RageShoTT** [comment]
we tried a good amonut of stuff on issue #1109 as the user was active while i also was, @Yuki-Codes there is a condition in which Anamnesis does work and it seems to be linked with xivlauncher, please look at the previously mentioned issue

**Comment by Yuki-Codes** [comment]
These errors look like they're actually #929, but the error messages are different due to the update:
Going to close this one and continue conversation over in #929.
