### ISSUE TITLE
Icons and body overlay missing in the Anamnesis

### ISSUE THREAD

**Issue by kyyiamorten** [imchillin/Anamnesis#1303]
**Description**
Bunch of icons and overlaid images do not load, e.g.: loading icon, folder icons in Import, body overlay in Posing tab.

**Steps to reproduce the behaviour:**
1. Load the application
2. Observe
3. Error: 
Shortcuts/AnamnesisBuiltIn.png
System.OverflowException: Dane obrazu wygenerowały przepełnienie podczas przetwarzania.
 ---> System.ArithmeticException: Overflow or underflow in the arithmetic operation.
   --- End of inner exception stack trace ---
   at System.Windows.Media.Imaging.ColorConvertedBitmap.FinalizeCreation()
   at System.Windows.Media.Imaging.ColorConvertedBitmap..ctor(BitmapSource source, ColorContext sourceColorContext, ColorContext destinationColorContext, PixelFormat format)
   at System.Windows.Media.Imaging.BitmapImage.FinalizeCreation()
   at System.Windows.Media.Imaging.BitmapImage.EndInit()
   at System.Windows.Media.Imaging.BitmapImage..ctor(Uri uriSource, RequestCachePolicy uriCachePolicy)
   at System.Windows.Media.Imaging.BitmapImage..ctor(Uri uriSource)
   at Anamnesis.Files.Shortcut..ctor(DirectoryInfo dir, String icon, String key)
   
1. Go to Posing tab
2. Observe missing body/face image.

1. Go to Posing tab
2. Click on Import
3. Observe

**Repeatability**
Bug occurred 25/25 attempts

**Expected behaviour**
Icons and body overlay visible

**Log file**
[2023-03-31-08-18-43.txt](https://github.com/imchillin/Anamnesis/files/11118833/2023-03-31-08-18-43.txt)
[2023-03-26-20-56-49.txt](https://github.com/imchillin/Anamnesis/files/11118837/2023-03-26-20-56-49.txt)
[2023-03-21-15-48-28.txt](https://github.com/imchillin/Anamnesis/files/11118839/2023-03-21-15-48-28.txt)

**Comment by StoiaCode** [comment]
Your .NET is out of date, try updating that.

**Comment by Ani-ki** [comment]
This is due to your Colour Management Settings in Windows and can be fixed by opening the Start menu, typing color management (or colour management depending on your language settings) and hitting Enter. From there, click on the Advanced  tab, and set Device profile to System default (sRGB IEC61966-2.1), then hit Close.

![image](https://user-images.githubusercontent.com/56663405/229042977-a052f090-8d5f-43b9-9d1a-199aec35c837.png)

**Comment by kyyiamorten** [comment]
Thank you, it helped!
