### ISSUE TITLE
Gibberish locale causes string format exceptions

### ISSUE THREAD

**Issue by Luna664** [imchillin/Anamnesis#266]
Hi, I just saw that the mode crashes when the Gibberish translation is activated, I attach the log I got

```C#
2021-04-11 09:21:52.273 +02:00 [INF] OS: Microsoft Windows 10.0.19042
2021-04-11 09:21:52.280 +02:00 [INF] Framework: .NET 5.0.4
2021-04-11 09:21:52.282 +02:00 [INF] OS Architecture: X64
2021-04-11 09:21:52.283 +02:00 [INF] Process Architecture: X64
2021-04-11 09:21:52.285 +02:00 [INF] Anamnesis Version: 2021-04-10 17:50:00 +10:00;2021.02.10.0000.0000
2021-04-11 09:21:52.286 +02:00 [INF] Initialized service: LogService
2021-04-11 09:21:52.297 +02:00 [INF] Initialized service: SerializerService
2021-04-11 09:21:52.333 +02:00 [INF] Initialized service: LocalizationService
2021-04-11 09:21:52.335 +02:00 [INF] Initialized service: ViewService
2021-04-11 09:21:52.410 +02:00 [INF] Module base: 140695976284160
2021-04-11 09:21:52.411 +02:00 [INF] Module size: 23334770
2021-04-11 09:21:53.258 +02:00 [INF] Took 844ms to scan for 11 addresses
2021-04-11 09:21:53.261 +02:00 [INF] Initialized service: MemoryService
2021-04-11 09:21:53.262 +02:00 [INF] Initialized service: AddressService
2021-04-11 09:21:53.264 +02:00 [INF] Initialized service: TargetService
2021-04-11 09:21:53.265 +02:00 [INF] Initialized service: FileService
2021-04-11 09:21:53.267 +02:00 [INF] Initialized service: TerritoryService
2021-04-11 09:21:53.268 +02:00 [INF] Initialized service: GameService
2021-04-11 09:21:53.270 +02:00 [INF] Initialized service: TimeService
2021-04-11 09:21:53.272 +02:00 [INF] Initialized service: CameraService
2021-04-11 09:21:53.273 +02:00 [INF] Initialized service: GposeService
2021-04-11 09:21:53.361 +02:00 [INF] Initialized service: SettingsService
2021-04-11 09:21:53.396 +02:00 [INF] Last update check was less than 6 hours ago. Skipping.
2021-04-11 09:21:53.398 +02:00 [INF] Initialized service: UpdateService
2021-04-11 09:21:54.724 +02:00 [INF] Initialized service: GameDataService
2021-04-11 09:21:54.745 +02:00 [INF] Initialized service: PoseService
2021-04-11 09:21:54.747 +02:00 [INF] Initialized service: TipService
2021-04-11 09:21:54.951 +02:00 [INF] Initialized service: TexToolsService
2021-04-11 09:21:55.060 +02:00 [INF] Retargeting actor: R.N. Success: True. Checked 65 actors.
2021-04-11 09:21:57.251 +02:00 [INF] Started application in 5060ms
2021-04-11 09:21:58.290 +02:00 [INF] Retargeting actor: R.N. Success: True. Checked 1 actors.
2021-04-11 09:22:40.093 +02:00 [ERR] Failed to bind skeleton to view
System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
   at System.Text.ValueStringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(String format, Object[] args)
   at Anamnesis.Services.LocalizationService.GetStringFormatted(String key, String[] param) in C:\Users\Luna\source\repos\Anamnesis\Anamnesis\Services\LocalizationService.cs:line 86
   at Anamnesis.Styles.Controls.TextBlock.LoadString() in C:\Users\Luna\source\repos\Anamnesis\Anamnesis\Styles\Controls\TextBlock.xaml.cs:line 91
   at Anamnesis.Styles.Controls.TextBlock.OnValueChanged(TextBlock sender, String val) in C:\Users\Luna\source\repos\Anamnesis\Anamnesis\Styles\Controls\TextBlock.xaml.cs:line 53
   at Anamnesis.Styles.DependencyProperties.Binder.<>c__DisplayClass1_0`2.<Register>b__0(DependencyObject d, DependencyPropertyChangedEventArgs e) in C:\Users\Luna\source\repos\Anamnesis\Anamnesis\Styles\DependencyProperties\Binder.cs:line 26
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.Controls.TextBlock.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState(Int32 k, ICollectionView collectionView, Object newValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.ClrBindingWorker.OnSourcePropertyChanged(Object o, String propName)
   at System.Windows.WeakEventManager.ListenerList`1.DeliverEvent(Object sender, EventArgs e, Type managerType)
   at System.ComponentModel.PropertyChangedEventManager.OnPropertyChanged(Object sender, PropertyChangedEventArgs args)
   at Anamnesis.PoseModule.Pages.PosePage.set_Skeleton(SkeletonVisual3d value) in C:\Users\Luna\source\repos\Anamnesis\Anamnesis\Posing\Pages\PosePage.xaml.cs:line 46
   at Anamnesis.PoseModule.Pages.PosePage.OnDataContextChanged(Object sender, DependencyPropertyChangedEventArgs e) in C:\Users\Luna\source\repos\Anamnesis\Anamnesis\Posing\Pages\PosePage.xaml.cs:line 99
2021-04-11 09:22:40.093 +02:00 [WRN] Took 196ms to tick memory
2021-04-11 09:22:40.414 +02:00 [WRN] Took 143ms to tick memory
```

**Comment by Yuuki-Walsh** [comment]
Now that we have actual localizations, I'll just remove the gibberish test locale instead of trying to fix this.
