### ISSUE TITLE
Crash when saving poses for Carbuncles

### ISSUE THREAD

**Issue by Lionheart237** [imchillin/Anamnesis#269]
This has been a problem since the custom skeleton was bundled with the program. Doesn't happen on the Ruby Carbuncle, which isn't listed on the model IDs in the skeleton's JSON file, so it's never loaded.

Log:

[2021-04-12-18-21-15.txt](https://github.com/imchillin/Anamnesis/files/6300136/2021-04-12-18-21-15.txt)

Raw error text:

2021-04-12 18:22:06.661 -04:00 [FTL] An item with the same key has already been added. Key: 
System.ArgumentException: An item with the same key has already been added. Key: 
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Anamnesis.Files.PoseFile.WriteToFile(ActorViewModel actor, SkeletonVisual3d skeleton, Configuration config) in C:\Users\k1l7j\source\repos\Anamnesis\Anamnesis\Files\PoseFile.cs:line 82
   at Anamnesis.Files.PoseFile.Save(ActorViewModel actor, SkeletonVisual3d skeleton, Configuration config) in C:\Users\k1l7j\source\repos\Anamnesis\Anamnesis\Files\PoseFile.cs:line 54
   at Anamnesis.PoseModule.Pages.PosePage.OnSaveClicked(Object sender, RoutedEventArgs e) in C:\Users\k1l7j\source\repos\Anamnesis\Anamnesis\Posing\Pages\PosePage.xaml.cs:line 155
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Yuuki-Walsh** [comment]
looks like the carbuncle skeleton file has a couple of bones with empty names, which isn't a problem when running the app, but it a problem when saving the pose.

I'll add some validation to ensure the skeleton file has no duplicate bone names, and remove the duplicate entries.
