### ISSUE TITLE
NPCs with no clothes, bones not loading properly

### ISSUE THREAD

**Issue by ajiiisai** [imchillin/Anamnesis#400]
Some people are having an issue with NPCs loading without clothes, I asked them for logs and found the same errors in all of them:
```
2021-06-07 23:06:21.061 +02:00 [WRN] Failed to update camera System.Exception: Failed to read gpose address
   at Anamnesis.Core.Memory.AddressService.get_GPoseCamera() in D:\Projects\Anamnesis\Anamnesis\Core\Memory\AddressService.cs:line 119
   at Anamnesis.CameraService.Tick()
2021-06-07 23:06:21.099 +02:00 [INF] Retargeting actor: A.A. Success: True. Checked 11 actors.
2021-06-07 23:06:21.408 +02:00 [WRN] Failed to update camera
```
and this:
```
2021-06-07 23:06:48.106 +02:00 [INF] Loaded skeleton file: Data/Skeletons/Middy.json
2021-06-07 23:06:49.778 +02:00 [WRN] UI thread took 62ms to tick
2021-06-07 23:06:54.335 +02:00 [WRN] UI thread took 73ms to tick
2021-06-07 23:06:55.526 +02:00 [WRN] UI thread took 55ms to tick
2021-06-07 23:07:10.459 +02:00 [WRN] Bone: "TailA" not found
2021-06-07 23:07:10.459 +02:00 [WRN] Bone: "TailB" not found
2021-06-07 23:07:10.459 +02:00 [WRN] Bone: "TailC" not found
2021-06-07 23:07:10.459 +02:00 [WRN] Bone: "TailD" not found
2021-06-07 23:07:10.459 +02:00 [WRN] Bone: "TailE" not found
2021-06-07 23:07:10.467 +02:00 [WRN] Bone: "ExRootHair" not found
2021-06-07 23:07:10.467 +02:00 [WRN] Bone: "ExHairA" not found
2021-06-07 23:07:10.467 +02:00 [WRN] Bone: "ExHairB" not found
2021-06-07 23:07:10.467 +02:00 [WRN] Bone: "ExHairC" not found
2021-06-07 23:07:10.467 +02:00 [WRN] Bone: "ExHairD" not found
2021-06-07 23:07:10.467 +02:00 [WRN] Bone: "ExHairE" not found
2021-06-07 23:07:10.468 +02:00 [WRN] Bone: "ExHairF" not found
2021-06-07 23:07:10.468 +02:00 [WRN] Bone: "ExHairG" not found
2021-06-07 23:07:10.468 +02:00 [WRN] Bone: "ExHairH" not found
2021-06-07 23:07:10.468 +02:00 [WRN] Bone: "ExHairI" not found
2021-06-07 23:07:10.468 +02:00 [WRN] Bone: "ExHairJ" not found
2021-06-07 23:07:10.468 +02:00 [WRN] Bone: "ExHairK" not found
................
```
I can't look to much into it right now but my wild guess is that it has something to do with GPose memory address. I also saw we updated Lumina so maybe some incompabilities there as well.

**Comment by ajiiisai** [comment]
Forgot to mention, all of this was on Windows 10 machines so I don't think it's the memory layout.

**Comment by Yuuki-Walsh** [comment]
going to keep tracking this over at #390
