### ISSUE TITLE
Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by Kumamond** [imchillin/Anamnesis#496]
as the tittle,when i try to open it,it showed me a strange error
it is log file shows:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Lumina.Excel.ExcelSheetImpl.ProcessDataRow(Int64 offset, Byte[] fileData)
   at Lumina.Excel.ExcelSheetImpl.ProcessDataEndianness(ExcelDataFile file)
   at Lumina.Excel.ExcelSheetImpl.GenerateFilePages()
   at Lumina.Excel.ExcelModule.CreateNewSheet[T](String name, Language language, Nullable`1 expectedHash, Tuple`2 key, Tuple`2 noLangKey)
   at Lumina.Excel.ExcelModule.GetSheet[T](String name, Language language, Nullable`1 expectedHash)
   at Lumina.Excel.ExcelModule.GetSheet[T](Language language)
   at Lumina.Excel.ExcelModule.GetSheet[T]()
   at Lumina.GameData.GetExcelSheet[T]()
   at Anamnesis.GameData.Sheets.LuminaSheet`3..ctor(GameData lumina)
   at Anamnesis.Services.GameDataService.Initialize()
   at Anamnesis.Services.ServiceManager.Add[T]()
2021-08-29 22:44:44.535 +08:00 [WRN] UI thread took 476ms to tick

**Comment by Ani-ki** [comment]
It is best practice to read the wiki, especially the Troubleshooting page, before opening tickets.

[**Are you using the Korean or Chinese version of the game? If so,  Anamnesis is not yet supported. Please use Concept Matrix until support is added for your client.**](https://github.com/imchillin/Anamnesis/wiki/Troubleshooting#basic-troubleshooting)

**Comment by Kumamond** [comment]
> 最佳做法是在开票前阅读 wiki，尤其是故障排除页面。
> 
> [**你用的是韩文版还是中文版的游戏？如果是这样，则尚不支持 Anamnesis。请使用概念矩阵，直到为您的客户添加支持。**](https://github.com/imchillin/Anamnesis/wiki/Troubleshooting#basic-troubleshooting)

我用的中文版...感谢您的回答！
