### ISSUE TITLE
Error when trying to select Dyes for any item

### ISSUE THREAD

**Issue by galaxybomb** [imchillin/Anamnesis#528]
2021-09-26 10:50:44.442 -04:00 [INF] OS: Microsoft Windows 10.0.19043
2021-09-26 10:50:44.443 -04:00 [INF] Framework: .NET 5.0.6
2021-09-26 10:50:44.443 -04:00 [INF] OS Architecture: X64
2021-09-26 10:50:44.443 -04:00 [INF] Process Architecture: X64
2021-09-26 10:50:44.443 -04:00 [INF] Anamnesis Version: 9/25/2021 11:55:42 AM
2021-09-26 10:50:44.443 -04:00 [INF] Check Working Directory: "C:\Users\tmdm9\Desktop\Anemsis"
2021-09-26 10:50:44.455 -04:00 [INF] Initialized service: LogService
2021-09-26 10:50:44.460 -04:00 [INF] Initialized service: SerializerService
2021-09-26 10:50:44.490 -04:00 [INF] Initialized service: LocalizationService
2021-09-26 10:50:44.491 -04:00 [INF] Initialized service: ViewService
2021-09-26 10:50:44.518 -04:00 [INF] Initialized service: SettingsService
2021-09-26 10:50:44.600 -04:00 [INF] Module base: 140695691071488
2021-09-26 10:50:44.600 -04:00 [INF] Module size: 23493170
2021-09-26 10:50:45.060 -04:00 [WRN] UI thread took 104ms to tick
2021-09-26 10:50:45.597 -04:00 [INF] Took 995ms to scan for 20 addresses
2021-09-26 10:50:45.597 -04:00 [INF] Initialized service: MemoryService
2021-09-26 10:50:45.597 -04:00 [INF] Initialized service: AddressService
2021-09-26 10:50:45.598 -04:00 [INF] Initialized service: TargetService
2021-09-26 10:50:45.598 -04:00 [INF] Initialized service: FileService
2021-09-26 10:50:45.599 -04:00 [INF] Initialized service: TerritoryService
2021-09-26 10:50:45.599 -04:00 [INF] Initialized service: GameService
2021-09-26 10:50:45.600 -04:00 [INF] Initialized service: TimeService
2021-09-26 10:50:45.600 -04:00 [INF] Initialized service: CameraService
2021-09-26 10:50:45.600 -04:00 [INF] Initialized service: GposeService
2021-09-26 10:50:45.610 -04:00 [INF] Last update check was less than 6 hours ago. Skipping.
2021-09-26 10:50:45.610 -04:00 [INF] Initialized service: UpdateService
2021-09-26 10:50:46.636 -04:00 [INF] Initialized service: GameDataService
2021-09-26 10:50:46.653 -04:00 [INF] Initialized service: PoseService
2021-09-26 10:50:46.654 -04:00 [INF] Initialized service: TipService
2021-09-26 10:50:46.674 -04:00 [INF] Initialized service: TexToolsService
2021-09-26 10:50:46.687 -04:00 [INF] Initialized service: FavoritesService
2021-09-26 10:50:46.723 -04:00 [INF] Retargeted actor: M.B
2021-09-26 10:50:46.736 -04:00 [INF] Retargeted actor: M.B
2021-09-26 10:50:49.292 -04:00 [INF] Started application in 4877ms
2021-09-26 10:50:49.353 -04:00 [WRN] UI thread took 55ms to tick
2021-09-26 10:50:50.341 -04:00 [INF] Retargeted actor: M.B
2021-09-26 10:50:55.603 -04:00 [WRN] UI thread took 2362ms to tick
2021-09-26 10:50:58.994 -04:00 [WRN] UI thread took 124ms to tick
2021-09-26 10:50:59.740 -04:00 [DBG] Triggering actor refresh due to changed property: Equipment
2021-09-26 10:50:59.741 -04:00 [DBG] Triggering actor refresh due to changed property: Equipment
2021-09-26 10:51:03.843 -04:00 [DBG] Triggering actor refresh due to changed property: Equipment
2021-09-26 10:51:03.844 -04:00 [DBG] Triggering actor refresh due to changed property: Equipment
2021-09-26 10:51:06.134 -04:00 [FTL] A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Unable to sort because the IComparer.Compare() method returns inconsistent results. Either a value does not compare equal to itself, or one value repeatedly compared to another value yields different results. IComparer: 'System.Comparison`1[System.Int32]'.)
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Unable to sort because the IComparer.Compare() method returns inconsistent results. Either a value does not compare equal to itself, or one value repeatedly compared to another value yields different results. IComparer: 'System.Comparison`1[System.Int32]'.)
 ---> System.ArgumentException: Unable to sort because the IComparer.Compare() method returns inconsistent results. Either a value does not compare equal to itself, or one value repeatedly compared to another value yields different results. IComparer: 'System.Comparison`1[System.Int32]'.
   at System.Collections.Generic.ArraySortHelper`1.Sort(Span`1 keys, Comparison`1 comparer)
   at System.MemoryExtensions.Sort[T](Span`1 span, Comparison`1 comparison)
   at System.Linq.EnumerableSorter`2.QuickSort(Int32[] keys, Int32 lo, Int32 hi)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.GetEnumerator()+MoveNext()
   at Anamnesis.Styles.Drawers.SelectorDrawer.<>c__DisplayClass66_0.<DoFilter>b__1()
   at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
--- End of stack trace from previous location ---
   at Anamnesis.Styles.Drawers.SelectorDrawer.DoFilter()
   --- End of inner exception stack trace ---

**Comment by Ani-ki** [comment]
This has already been reported in #524

Please do not open duplicate tickets.
