### ISSUE TITLE
Can't load poses out of .cmp or .pose data

### ISSUE THREAD

**Issue by DevilsCreed** [imchillin/Anamnesis#535]
Been tryn to load a couple of poses from .cpm files and .pose files and getteing the same error over and over. Dunno why.
C/P from the logfile. Maybe you can figure out the problem.
Keep up the good work.
---------------------------------------------------------------------------------------------------------------------------
2021-09-29 11:31:43.468 +02:00 [INF] OS: Microsoft Windows 10.0.19042
2021-09-29 11:31:43.469 +02:00 [INF] Framework: .NET 5.0.3
2021-09-29 11:31:43.469 +02:00 [INF] OS Architecture: X64
2021-09-29 11:31:43.469 +02:00 [INF] Process Architecture: X64
2021-09-29 11:31:43.469 +02:00 [INF] Anamnesis Version: 29.09.2021 07:55:36
2021-09-29 11:31:43.469 +02:00 [INF] Check Working Directory: "D:\Anamnesis"
2021-09-29 11:31:43.477 +02:00 [INF] Initialized service: LogService
2021-09-29 11:31:43.481 +02:00 [INF] Initialized service: SerializerService
2021-09-29 11:31:43.504 +02:00 [INF] Initialized service: LocalizationService
2021-09-29 11:31:43.505 +02:00 [INF] Initialized service: ViewService
2021-09-29 11:31:43.528 +02:00 [INF] Initialized service: SettingsService
2021-09-29 11:31:43.582 +02:00 [INF] Module base: 140702945251328
2021-09-29 11:31:43.582 +02:00 [INF] Module size: 23493170
2021-09-29 11:31:44.057 +02:00 [WRN] UI thread took 62ms to tick
2021-09-29 11:31:44.762 +02:00 [INF] Took 1179ms to scan for 20 addresses
2021-09-29 11:31:44.763 +02:00 [INF] Initialized service: MemoryService
2021-09-29 11:31:44.763 +02:00 [INF] Initialized service: AddressService
2021-09-29 11:31:44.763 +02:00 [INF] Initialized service: TargetService
2021-09-29 11:31:44.763 +02:00 [INF] Initialized service: FileService
2021-09-29 11:31:44.763 +02:00 [INF] Initialized service: TerritoryService
2021-09-29 11:31:44.763 +02:00 [INF] Initialized service: GameService
2021-09-29 11:31:44.764 +02:00 [INF] Initialized service: TimeService
2021-09-29 11:31:44.764 +02:00 [INF] Initialized service: CameraService
2021-09-29 11:31:44.764 +02:00 [INF] Initialized service: GposeService
2021-09-29 11:31:44.768 +02:00 [INF] Last update check was less than 6 hours ago. Skipping.
2021-09-29 11:31:44.768 +02:00 [INF] Initialized service: UpdateService
2021-09-29 11:31:45.650 +02:00 [INF] Initialized service: GameDataService
2021-09-29 11:31:45.670 +02:00 [INF] Initialized service: PoseService
2021-09-29 11:31:45.671 +02:00 [INF] Initialized service: TipService
2021-09-29 11:31:45.694 +02:00 [INF] Initialized service: TexToolsService
2021-09-29 11:31:45.699 +02:00 [INF] Initialized service: FavoritesService
2021-09-29 11:31:45.750 +02:00 [INF] Retargeted actor: I.L
2021-09-29 11:31:45.773 +02:00 [INF] Retargeted actor: I.L
2021-09-29 11:31:47.660 +02:00 [WRN] Missing Localized string: "Help_Title" in locale: "DE"
2021-09-29 11:31:47.661 +02:00 [WRN] Missing Localized string: "Help_Tip" in locale: "DE"
2021-09-29 11:31:48.167 +02:00 [WRN] Missing Localized string: "Help_Title" in locale: "DE"
2021-09-29 11:31:48.388 +02:00 [INF] Started application in 4943ms
2021-09-29 11:31:49.433 +02:00 [INF] Retargeted actor: I.L
2021-09-29 11:31:56.413 +02:00 [WRN] Failed to update camera
System.Exception: Failed to read gpose address
   at Anamnesis.Core.Memory.AddressService.get_GPoseCamera()
   at Anamnesis.CameraService.Tick()
2021-09-29 11:31:56.435 +02:00 [INF] Retargeted actor: I.L
2021-09-29 11:31:57.462 +02:00 [INF] Retargeted actor: I.L
2021-09-29 11:32:03.563 +02:00 [INF] Loaded skeleton file: Data/Skeletons/Middy.json
2021-09-29 11:32:06.833 +02:00 [WRN] Missing Localized string: "Pose_ScalePack" in locale: "DE"
2021-09-29 11:32:06.841 +02:00 [WRN] Missing Localized string: "Pose_ScalePack" in locale: "DE"
2021-09-29 11:32:08.341 +02:00 [WRN] Missing Localized string: "FileBrowser_Sort" in locale: "DE"
2021-09-29 11:32:08.341 +02:00 [WRN] Missing Localized string: "FileBrowser_SortAlpha" in locale: "DE"
2021-09-29 11:32:08.341 +02:00 [WRN] Missing Localized string: "FileBrowser_SortDate" in locale: "DE"
2021-09-29 11:32:08.382 +02:00 [WRN] Missing Localized string: "FileBrowser_BrowseKey" in locale: "DE"
2021-09-29 11:32:08.474 +02:00 [WRN] Missing Localized string: "FileBrowser_BrowseKey" in locale: "DE"
2021-09-29 11:32:13.628 +02:00 [ERR] Failed to load pose file
System.Exception: Failed to parse string: .cmp to byte array
 ---> System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Byte.Parse(String s, NumberStyles style)
   at Anamnesis.Files.LegacyPoseFile.StringToByteArray(String hex)
   --- End of inner exception stack trace ---
   at Anamnesis.Files.LegacyPoseFile.StringToByteArray(String hex)
   at Anamnesis.Files.LegacyPoseFile.StringToBone(String rot, String scale, String position)
   at Anamnesis.Files.LegacyPoseFile.Upgrade(Races race)
   at Anamnesis.PoseModule.Pages.PosePage.Open(Boolean selectionOnly, Boolean scaleOnly)

**Comment by Ani-ki** [comment]
This was resolved in the **[hotfix that was just released](https://github.com/imchillin/Anamnesis/releases/tag/v2021-09-29-beta)**.
