### ISSUE TITLE
Crashing when I try to load any poses. This is after the bugfix.

### ISSUE THREAD

**Issue by GeoS3VEN** [imchillin/Anamnesis#553]
**Describe the bug**
When I try to load any pose, it causes Anamnesis to crash and close.

**To Reproduce**
After freezing all movement in gpose, i go to my character pose tab and press load. 
Once i press load it crashes immediately. 

**Expected behaviour**
I expected it to open a browser window so i could select a pose to load.

I have reinstalled, but the error keeps occuring.

**Log file**
[2021-10-01-19-53-49.txt](https://github.com/imchillin/Anamnesis/files/7266945/2021-10-01-19-53-49.txt)

2021-10-01 19:53:49.623 +08:00 [INF] OS: Microsoft Windows 10.0.19041
2021-10-01 19:53:49.626 +08:00 [INF] Framework: .NET 5.0.9
2021-10-01 19:53:49.627 +08:00 [INF] OS Architecture: X64
2021-10-01 19:53:49.627 +08:00 [INF] Process Architecture: X64
2021-10-01 19:53:49.627 +08:00 [INF] Anamnesis Version: 9/29/2021 9:19:02 AM
2021-10-01 19:53:49.627 +08:00 [INF] Check Working Directory: "E:\Program Files\Anamnesis"
2021-10-01 19:53:49.637 +08:00 [INF] Initialized service: LogService
2021-10-01 19:53:49.642 +08:00 [INF] Initialized service: SerializerService
2021-10-01 19:53:49.694 +08:00 [INF] Initialized service: LocalizationService
2021-10-01 19:53:49.695 +08:00 [INF] Initialized service: ViewService
2021-10-01 19:53:49.731 +08:00 [INF] Initialized service: SettingsService
2021-10-01 19:53:49.802 +08:00 [INF] Module base: 140696128000000
2021-10-01 19:53:49.803 +08:00 [INF] Module size: 23493170
2021-10-01 19:53:50.357 +08:00 [WRN] UI thread took 82ms to tick
2021-10-01 19:53:51.357 +08:00 [WRN] UI thread took 73ms to tick
2021-10-01 19:53:52.177 +08:00 [WRN] UI thread took 86ms to tick
2021-10-01 19:53:52.304 +08:00 [INF] Took 2501ms to scan for 20 addresses
2021-10-01 19:53:52.305 +08:00 [INF] Initialized service: MemoryService
2021-10-01 19:53:52.305 +08:00 [INF] Initialized service: AddressService
2021-10-01 19:53:52.305 +08:00 [INF] Initialized service: TargetService
2021-10-01 19:53:52.305 +08:00 [INF] Initialized service: FileService
2021-10-01 19:53:52.306 +08:00 [INF] Initialized service: TerritoryService
2021-10-01 19:53:52.306 +08:00 [INF] Initialized service: GameService
2021-10-01 19:53:52.306 +08:00 [INF] Initialized service: TimeService
2021-10-01 19:53:52.306 +08:00 [INF] Initialized service: CameraService
2021-10-01 19:53:52.306 +08:00 [INF] Initialized service: GposeService
2021-10-01 19:53:52.312 +08:00 [INF] Last update check was less than 6 hours ago. Skipping.
2021-10-01 19:53:52.312 +08:00 [INF] Initialized service: UpdateService
2021-10-01 19:53:53.658 +08:00 [INF] Initialized service: GameDataService
2021-10-01 19:53:53.729 +08:00 [INF] Initialized service: PoseService
2021-10-01 19:53:53.729 +08:00 [WRN] UI thread took 68ms to tick
2021-10-01 19:53:53.729 +08:00 [INF] Initialized service: TipService
2021-10-01 19:53:53.740 +08:00 [INF] Initialized service: TexToolsService
2021-10-01 19:53:53.751 +08:00 [INF] Initialized service: FavoritesService
2021-10-01 19:53:53.791 +08:00 [INF] Retargeted actor: L.W
2021-10-01 19:53:53.806 +08:00 [INF] Retargeted actor: L.W
2021-10-01 19:53:54.872 +08:00 [INF] Retargeted actor: L.W
2021-10-01 19:53:57.177 +08:00 [INF] Started application in 7579ms
2021-10-01 19:53:57.230 +08:00 [WRN] UI thread took 52ms to tick
2021-10-01 19:54:02.292 +08:00 [INF] Loaded skeleton file: Data/Skeletons/Middy.json
2021-10-01 19:54:05.039 +08:00 [FTL] A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Could not find a part of the path 'C:\Users\Admin\Documents\Anamnesis\Poses'.)
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Could not find a part of the path 'C:\Users\Admin\Documents\Anamnesis\Poses'.)
 ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Admin\Documents\Anamnesis\Poses'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.DirectoryInfos(String directory, String expression, EnumerationOptions options, Boolean isNormalized)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.DirectoryInfo.GetDirectories(String searchPattern, EnumerationOptions enumerationOptions)
   at Anamnesis.GUI.Views.FileBrowserView.UpdateEntries()
   --- End of inner exception stack trace ---

**Comment by Ani-ki** [comment]
This is being discussed in #551 and has been resolved pending an update. Per the bug report instructions, please check closed tickets in future in case your issue has already been resolved and is awaiting a release, as duplicate tickets will be closed without notice.

**Comment by GeoS3VEN** [comment]
Is this not already fixed in the current update? or has that update not gone live yet?

**Comment by Ani-ki** [comment]
As I said, pending an update. We don't like pushing updates for single fixes (hotfixes to resolve fatal errors notwithstanding), so we're going to work on a few other things and push an update out some time this week, free time and work depending.
