### ISSUE TITLE
Critical Error Upon Launch

### ISSUE THREAD

**Issue by Nevinci** [imchillin/Anamnesis#604]
**Describe the bug**
Whenever I attempt to open the app it launches normally but when it detects the ffxiv process it throws a critical error 100% of the time.

**To Reproduce**
1. Open The App
2. Receive Critical error

**Expected behavior**
What I expected to happen is the app opens like it usually does, It stopped working roughly 2 weeks ago so I don't believe it was the Windows 11 update and the file is up to date so I'm a tad lost honestly.

**Log file**
[2021-11-03-23-41-44.txt](https://github.com/imchillin/Anamnesis/files/7472814/2021-11-03-23-41-44.txt)

2021-11-03 23:41:44.556 -07:00 [INF] OS: Microsoft Windows 10.0.22000
2021-11-03 23:41:44.557 -07:00 [INF] Framework: .NET 5.0.9
2021-11-03 23:41:44.557 -07:00 [INF] OS Architecture: X64
2021-11-03 23:41:44.557 -07:00 [INF] Process Architecture: X64
2021-11-03 23:41:44.557 -07:00 [INF] Anamnesis Version: 2021-10-30 09:44
2021-11-03 23:41:44.558 -07:00 [INF] Check Working Directory: "C:\SquareEnix\FINAL FANTASY XIV - A Realm Reborn\Anamnesis"
2021-11-03 23:41:44.568 -07:00 [INF] Initialized service: LogService
2021-11-03 23:41:44.572 -07:00 [INF] Initialized service: SerializerService
2021-11-03 23:41:44.595 -07:00 [INF] Initialized service: LocalizationService
2021-11-03 23:41:44.596 -07:00 [INF] Initialized service: ViewService
2021-11-03 23:41:44.622 -07:00 [INF] Initialized service: SettingsService
2021-11-03 23:41:44.646 -07:00 [INF] Module base: 140699251904512
2021-11-03 23:41:44.646 -07:00 [INF] Module size: 23493170
2021-11-03 23:41:45.265 -07:00 [WRN] UI thread took 152ms to tick
2021-11-03 23:41:46.160 -07:00 [WRN] UI thread took 118ms to tick
2021-11-03 23:41:46.343 -07:00 [INF] Took 1696ms to scan for 20 addresses
2021-11-03 23:41:46.343 -07:00 [INF] Initialized service: MemoryService
2021-11-03 23:41:46.344 -07:00 [INF] Initialized service: AddressService
2021-11-03 23:41:46.344 -07:00 [INF] Initialized service: TargetService
2021-11-03 23:41:46.344 -07:00 [INF] Initialized service: FileService
2021-11-03 23:41:46.344 -07:00 [INF] Initialized service: TerritoryService
2021-11-03 23:41:46.344 -07:00 [INF] Initialized service: GameService
2021-11-03 23:41:46.344 -07:00 [INF] Initialized service: TimeService
2021-11-03 23:41:46.345 -07:00 [INF] Initialized service: CameraService
2021-11-03 23:41:46.345 -07:00 [INF] Initialized service: GposeService
2021-11-03 23:41:46.426 -07:00 [FTL] UpdateService Error: The requested address is not valid in its context. (api.github.com:443)
System.Net.Http.HttpRequestException: The requested address is not valid in its context. (api.github.com:443)
 ---> System.Net.Sockets.SocketException (10049): The requested address is not valid in its context.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.DefaultConnectAsync(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Anamnesis.Updater.UpdateService.CheckForUpdates()
   at Anamnesis.Updater.UpdateService.Initialize()
   at Anamnesis.Services.ServiceManager.Add[T]()

**Comment by Ani-ki** [comment]
Unfortunately nothing on your log file shows any error with the tool itself, instead just issues with the uodate service not connecting to Github. Do you have any other log files?

**Comment by Ani-ki** [comment]
It's because it can't connect to Github. There's nothing either of us can do from your end in this case.

**Comment by Nevinci** [comment]
Alright thank you for your time, After I get off work I can try some more things on my end to see if something fixes. If not I will just wait and see if it just works at some point.

**Comment by Ani-ki** [comment]
Likewise, am just starting work myself.

**Comment by Yuuki-Walsh** [comment]
I've reduced the severity of this error form Fatal to Error, you'll still get the error message as long as you cant connect to GitHUB, but it wont kill the entire application anymore.

**Comment by Nevinci** [comment]
Alright appreciate it, Thank you.
