### ISSUE TITLE
Failed to bind skeleton to view (Folder path doesn't exist)

### ISSUE THREAD

**Issue by SaviorXTanren** [imchillin/Anamnesis#613]
Trying to build skeleton data for a prop when the folder path "Data\Skeletons" doesn't exist causes the skeleton generation to fail. Manually creating the folder path yourself resolves the issue.

Before trying to open the file create handle, there should be a check to make sure the directory path exists first and create it if it doesn't.

System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Matthew\Downloads\Anamnesis\Data\Skeletons\Generated_469_0_0.json'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamWriter..ctor(String path)
   at System.IO.File.WriteAllText(String path, String contents)
   at Anamnesis.Serialization.SerializerService.SerializeFile(String path, Object obj)
   at Anamnesis.PoseModule.PoseService.SaveTemplate(SkeletonTemplateFile skeleton)
   at Anamnesis.PoseModule.SkeletonVisual3d.Generate(SkeletonMemory memory, Boolean forceGenerateParenting)
   at Anamnesis.PoseModule.SkeletonVisual3d.GenerateBones(Boolean forceGenerateParenting)
   at Anamnesis.PoseModule.PoseService.GetVisual(ActorMemory actor)
   at Anamnesis.PoseModule.Pages.PosePage.OnDataContextChanged(Object sender, DependencyPropertyChangedEventArgs e)

[2021-11-07-22-52-33.txt](https://github.com/imchillin/Anamnesis/files/7494823/2021-11-07-22-52-33.txt)

**Comment by Ani-ki** [comment]
Duplicate issue, already being discussed in #609.
