### ISSUE TITLE
Critical Error failed to initialize lumina

### ISSUE THREAD

**Issue by Alastor6Alejandro** [imchillin/Anamnesis#674]
loaded the program and it wont start. Just says critical Error failed to initialize Lumina. 

1. Clicked Anamnesis
2. Gives me the Critical Error failed to initialize lumina

2021-12-12 10:06:31.664 -05:00 [INF] OS: Microsoft Windows 10.0.22000
2021-12-12 10:06:31.665 -05:00 [INF] Framework: .NET 5.0.9
2021-12-12 10:06:31.665 -05:00 [INF] OS Architecture: X64
2021-12-12 10:06:31.665 -05:00 [INF] Process Architecture: X64
2021-12-12 10:06:31.665 -05:00 [INF] Anamnesis Version: 2021-12-11 22:24
2021-12-12 10:06:31.665 -05:00 [INF] Check Working Directory: "C:\Users\shado\Downloads"
2021-12-12 10:06:31.677 -05:00 [INF] Initialized service: LogService
2021-12-12 10:06:31.682 -05:00 [INF] Initialized service: SerializerService
2021-12-12 10:06:31.712 -05:00 [INF] Initialized service: LocalizationService
2021-12-12 10:06:31.716 -05:00 [INF] Initialized service: ViewService
2021-12-12 10:06:31.744 -05:00 [INF] Initialized service: SettingsService
2021-12-12 10:06:31.848 -05:00 [INF] Module base: 140698693079040
2021-12-12 10:06:31.848 -05:00 [INF] Module size: 24104578
2021-12-12 10:06:32.913 -05:00 [INF] Took 1064ms to scan for 19 addresses
2021-12-12 10:06:32.913 -05:00 [INF] Initialized service: MemoryService
2021-12-12 10:06:32.914 -05:00 [INF] Initialized service: AddressService
2021-12-12 10:06:32.914 -05:00 [INF] Initialized service: TargetService
2021-12-12 10:06:32.914 -05:00 [INF] Initialized service: FileService
2021-12-12 10:06:32.914 -05:00 [INF] Initialized service: TerritoryService
2021-12-12 10:06:32.914 -05:00 [INF] Initialized service: GameService
2021-12-12 10:06:32.915 -05:00 [INF] Initialized service: TimeService
2021-12-12 10:06:32.915 -05:00 [INF] Initialized service: CameraService
2021-12-12 10:06:32.915 -05:00 [INF] Initialized service: GposeService
2021-12-12 10:06:32.924 -05:00 [INF] Last update check was less than 6 hours ago. Skipping.
2021-12-12 10:06:32.924 -05:00 [INF] Initialized service: UpdateService
2021-12-12 10:06:32.927 -05:00 [INF] Found game version: 2021.11.28.0000.0000
2021-12-12 10:06:32.930 -05:00 [INF] Found game client region: Global
2021-12-12 10:06:33.204 -05:00 [FTL] GameDataService Error: Failed to initialize Lumina (Are your game files up to date?)
System.Exception: Failed to initialize Lumina (Are your game files up to date?)
 ---> System.ArgumentException: An item with the same key has already been added. Key: 0
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](List`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Lumina.Data.SqPackIndex.LoadIndex()
   at Lumina.Data.Repository.SetupIndexes()
   at Lumina.GameData..ctor(String dataPath, LuminaOptions options)
   at Anamnesis.Services.GameDataService.Initialize()
   --- End of inner exception stack trace ---
   at Anamnesis.Services.GameDataService.Initialize()
   at Anamnesis.Services.ServiceManager.Add[T]()
2021-12-12 10:06:41.634 -05:00 [INF] 519Mb memory In use.

**Comment by Yuki-Walsh** [comment]
This is a werid onw, your game files might be corrupt?
Do you have mods installed? have you tried fresh indexes from Tex Tools or a clean game install?

**Comment by Alastor6Alejandro** [comment]
Still nothing . Fresh re-install of the game, no mods due to start over feature, added to avg and malewarebtyes exception. framework is up to 5.0.12. using the latest ana. and still same issue.
If it helps, heres a pic of he issue
![error](https://user-images.githubusercontent.com/96012758/146004252-046d43d1-cd79-4628-9078-4ff606f2e33f.png)

**Comment by Ani-ki** [comment]
A this stage your best option is to wait until the next update- we currently have one in closed testing, so we should have this out in the next couple of days.
