### ISSUE TITLE
Failed to extract standard pose library error

### ISSUE THREAD

**Issue by TheePhrog** [imchillin/Anamnesis#681]
**Describe the bug**
Issue where loading character models and poses refuses to work, trying to save a pose crashes the program

**To Reproduce**
Steps to reproduce the behaviour:
1. Start Anamnesis
2. Get failed to extract standard pose library error
3. Be confused
4. Cry

**Expected behaviour**
Should be able to load poses and models without issue

**Log file**
2021-12-13 02:16:59.485 -05:00 [INF] OS: Microsoft Windows 10.0.19043
2021-12-13 02:16:59.486 -05:00 [INF] Framework: .NET 5.0.12
2021-12-13 02:16:59.486 -05:00 [INF] OS Architecture: X64
2021-12-13 02:16:59.487 -05:00 [INF] Process Architecture: X64
2021-12-13 02:16:59.487 -05:00 [INF] Anamnesis Version: 2021-12-11 22:24
2021-12-13 02:16:59.487 -05:00 [INF] Check Working Directory: "C:\Program Files (x86)\Anamnesis"
2021-12-13 02:16:59.506 -05:00 [INF] Initialized service: LogService
2021-12-13 02:16:59.511 -05:00 [INF] Initialized service: SerializerService
2021-12-13 02:16:59.535 -05:00 [INF] Initialized service: LocalizationService
2021-12-13 02:16:59.536 -05:00 [INF] Initialized service: ViewService
2021-12-13 02:16:59.573 -05:00 [INF] Initialized service: SettingsService
2021-12-13 02:16:59.766 -05:00 [INF] Module base: 140694858108928
2021-12-13 02:16:59.766 -05:00 [INF] Module size: 24104578
2021-12-13 02:17:01.061 -05:00 [INF] Took 1294ms to scan for 19 addresses
2021-12-13 02:17:01.062 -05:00 [INF] Initialized service: MemoryService
2021-12-13 02:17:01.063 -05:00 [INF] Initialized service: AddressService
2021-12-13 02:17:01.063 -05:00 [INF] Initialized service: TargetService
2021-12-13 02:17:01.063 -05:00 [INF] Initialized service: FileService
2021-12-13 02:17:01.063 -05:00 [INF] Initialized service: TerritoryService
2021-12-13 02:17:01.063 -05:00 [INF] Initialized service: GameService
2021-12-13 02:17:01.064 -05:00 [INF] Initialized service: TimeService
2021-12-13 02:17:01.065 -05:00 [INF] Initialized service: CameraService
2021-12-13 02:17:01.065 -05:00 [INF] Initialized service: GposeService
2021-12-13 02:17:01.071 -05:00 [INF] Last update check was less than 6 hours ago. Skipping.
2021-12-13 02:17:01.071 -05:00 [INF] Initialized service: UpdateService
2021-12-13 02:17:01.073 -05:00 [INF] Found game version: 2021.11.28.0000.0000
2021-12-13 02:17:01.078 -05:00 [INF] Found game client region: Global
2021-12-13 02:17:02.879 -05:00 [DBG] sheet Race not in cache - creating new sheet for language "English"
2021-12-13 02:17:02.891 -05:00 [DBG] sheet Tribe not in cache - creating new sheet for language "English"
2021-12-13 02:17:02.892 -05:00 [DBG] sheet Item not in cache - creating new sheet for language "English"
2021-12-13 02:17:02.961 -05:00 [DBG] sheet Stain not in cache - creating new sheet for language "English"
2021-12-13 02:17:02.961 -05:00 [DBG] sheet ENpcBase not in cache - creating new sheet for language "English"
2021-12-13 02:17:03.059 -05:00 [DBG] sheet BNpcBase not in cache - creating new sheet for language "English"
2021-12-13 02:17:03.066 -05:00 [DBG] sheet Mount not in cache - creating new sheet for language "English"
2021-12-13 02:17:03.068 -05:00 [DBG] sheet Companion not in cache - creating new sheet for language "English"
2021-12-13 02:17:03.070 -05:00 [DBG] sheet TerritoryType not in cache - creating new sheet for language "English"
2021-12-13 02:17:03.073 -05:00 [DBG] sheet Weather not in cache - creating new sheet for language "English"
2021-12-13 02:17:03.074 -05:00 [DBG] sheet CharaMakeCustomize not in cache - creating new sheet for language "English"
2021-12-13 02:17:03.076 -05:00 [DBG] sheet CharaMakeType not in cache - creating new sheet for language "English"
2021-12-13 02:17:03.079 -05:00 [DBG] sheet ENpcResident not in cache - creating new sheet for language "English"
2021-12-13 02:17:03.100 -05:00 [DBG] sheet PlaceName not in cache - creating new sheet for language "English"
2021-12-13 02:17:03.104 -05:00 [DBG] sheet Perform not in cache - creating new sheet for language "English"
2021-12-13 02:17:03.105 -05:00 [DBG] sheet WeatherRate not in cache - creating new sheet for language "English"
2021-12-13 02:17:03.106 -05:00 [DBG] sheet EquipRaceCategory not in cache - creating new sheet for language "English"
2021-12-13 02:17:03.107 -05:00 [DBG] sheet BNpcName not in cache - creating new sheet for language "English"
2021-12-13 02:17:03.113 -05:00 [INF] Initialized service: GameDataService
2021-12-13 02:17:03.113 -05:00 [INF] Initialized service: PoseService
2021-12-13 02:17:03.114 -05:00 [INF] Initialized service: TipService
2021-12-13 02:17:03.123 -05:00 [ERR] Failed to extract standard pose library
System.OverflowException: The image data generated an overflow during processing.
 ---> System.ArithmeticException: Overflow or underflow in the arithmetic operation.
   --- End of inner exception stack trace ---
   at System.Windows.Media.Imaging.ColorConvertedBitmap.FinalizeCreation()
   at System.Windows.Media.Imaging.ColorConvertedBitmap..ctor(BitmapSource source, ColorContext sourceColorContext, ColorContext destinationColorContext, PixelFormat format)
   at System.Windows.Media.Imaging.BitmapImage.FinalizeCreation()
   at System.Windows.Media.Imaging.BitmapImage.EndInit()
   at System.Windows.Media.Imaging.BitmapImage..ctor(Uri uriSource, RequestCachePolicy uriCachePolicy)
   at System.Windows.Media.Imaging.BitmapImage..ctor(Uri uriSource)
   at Anamnesis.Files.Shortcut..ctor(DirectoryInfo dir, String icon, String key)
   at Anamnesis.Files.FileService.get_StandardPoseDirectory()
   at Anamnesis.PoseModule.PoseService.ExtractStandardPoses()
2021-12-13 02:17:03.126 -05:00 [INF] Initialized service: TexToolsService
2021-12-13 02:17:03.167 -05:00 [DBG] sheet EquipSlotCategory not in cache - creating new sheet for language "English"
2021-12-13 02:17:03.169 -05:00 [DBG] sheet ClassJobCategory not in cache - creating new sheet for language "English"
2021-12-13 02:17:03.180 -05:00 [INF] Initialized service: FavoritesService
2021-12-13 02:17:03.604 -05:00 [INF] Retargeted actor: R.U
2021-12-13 02:17:03.616 -05:00 [INF] Retargeted actor: R.U
2021-12-13 02:17:05.694 -05:00 [INF] Loading gallery image list
2021-12-13 02:17:06.155 -05:00 [INF] Started application in 6701ms
2021-12-13 02:17:06.220 -05:00 [WRN] UI thread took 64ms to tick
2021-12-13 02:17:09.474 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:17:19.475 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:17:29.482 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:17:39.482 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:17:49.484 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:17:55.847 -05:00 [WRN] UI thread took 82ms to tick
2021-12-13 02:17:59.504 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:18:01.242 -05:00 [ERR] Failed to load appearance
System.OverflowException: The image data generated an overflow during processing.
 ---> System.ArithmeticException: Overflow or underflow in the arithmetic operation.
   --- End of inner exception stack trace ---
   at System.Windows.Media.Imaging.ColorConvertedBitmap.FinalizeCreation()
   at System.Windows.Media.Imaging.ColorConvertedBitmap..ctor(BitmapSource source, ColorContext sourceColorContext, ColorContext destinationColorContext, PixelFormat format)
   at System.Windows.Media.Imaging.BitmapImage.FinalizeCreation()
   at System.Windows.Media.Imaging.BitmapImage.EndInit()
   at System.Windows.Media.Imaging.BitmapImage..ctor(Uri uriSource, RequestCachePolicy uriCachePolicy)
   at System.Windows.Media.Imaging.BitmapImage..ctor(Uri uriSource)
   at Anamnesis.Files.Shortcut..ctor(DirectoryInfo dir, String icon, String key)
   at Anamnesis.Files.FileService.get_DefaultCharacterDirectory()
   at Anamnesis.Character.Pages.AppearancePage.Load(SaveModes mode)
2021-12-13 02:18:01.366 -05:00 [WRN] UI thread took 164ms to tick
2021-12-13 02:18:09.508 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:18:19.511 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:18:29.518 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:18:39.532 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:18:49.540 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:18:59.548 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:19:09.556 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:19:19.564 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:19:29.572 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:19:39.572 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:19:49.580 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:19:59.594 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:20:09.599 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:20:19.611 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:20:29.619 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:20:39.635 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:20:49.638 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:20:59.650 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:21:09.659 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:21:19.671 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:21:29.671 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:21:39.676 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:21:49.689 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:21:59.697 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:22:09.711 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:22:19.716 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:22:29.730 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:22:39.736 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:22:49.749 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:22:59.753 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:23:09.756 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:23:19.757 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:23:29.771 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:23:39.771 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:23:49.779 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:23:59.789 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:24:09.792 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:24:19.797 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:24:29.799 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:24:39.801 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:24:49.802 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:24:59.810 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:25:09.823 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:25:19.823 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:25:29.827 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:25:39.842 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:25:49.854 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:25:59.869 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:26:09.884 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:26:19.890 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:26:29.890 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:26:39.894 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:26:49.898 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:26:59.911 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:27:09.915 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:27:19.918 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:27:29.925 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:27:39.930 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:27:49.930 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:27:59.935 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:28:09.943 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:28:19.946 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:28:29.954 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:28:39.958 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:28:49.961 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:28:59.971 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:29:09.983 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:29:19.990 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:29:29.997 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:29:40.003 -05:00 [INF] 607Mb memory In use.
2021-12-13 02:29:50.020 -05:00 [INF] 607Mb memory In use.

**Comment by Ani-ki** [comment]
Please correct your colour management settings in Windows.

This can be done by opening the Start menu, typing `color management` (or `colour management` depending on your language settings) and hitting Enter. From there, click on the `Advanced` tab, and set `Device profile` to `System default (sRGB IEC61966-2.1)`, then hit Close.

**Comment by Yuki-Walsh** [comment]
we've caught this error, so in future the error will be displayed, but it wont crash the application.
