### ISSUE TITLE
Critical Error Anamnesis was unable to recover from this error and must close.

### ISSUE THREAD

**Issue by LadyLotus31** [imchillin/Anamnesis#684]
**Describe the bug**

loaded the program and it won't start. Just say Critical Error Anamnesis was unable to recover from this error and must close. 
1. Clicked Anamnesis
2. Gives me the Critical Error Anamnesis was unable to recover from this error and must close.

2021-12-13 07:48:44.428 -05:00 [INF] OS: Microsoft Windows 10.0.19043
2021-12-13 07:48:44.428 -05:00 [INF] Framework: .NET 5.0.7
2021-12-13 07:48:44.429 -05:00 [INF] OS Architecture: X64
2021-12-13 07:48:44.429 -05:00 [INF] Process Architecture: X64
2021-12-13 07:48:44.429 -05:00 [INF] Anamnesis Version: 7/26/2021 5:30:00 PM
2021-12-13 07:48:44.429 -05:00 [INF] Check Working Directory: "E:\SquareEnix\FINAL FANTASY XIV - A Realm Reborn\game\Anamnesis"
2021-12-13 07:48:44.446 -05:00 [INF] Initialized service: LogService
2021-12-13 07:48:44.449 -05:00 [INF] Initialized service: SerializerService
2021-12-13 07:48:44.461 -05:00 [INF] Initialized service: LocalizationService
2021-12-13 07:48:44.462 -05:00 [INF] Initialized service: ViewService
2021-12-13 07:48:44.483 -05:00 [INF] Initialized service: SettingsService
2021-12-13 07:49:06.823 -05:00 [INF] Module base: 140701238038528
2021-12-13 07:49:06.823 -05:00 [INF] Module size: 24104578
2021-12-13 07:49:06.952 -05:00 [FTL] Failed to scan memory for base address from signature (Have you tried restarting FFXIV?)
System.Collections.Generic.KeyNotFoundException: Can't find a signature of 4F 8B B4 C6 ?? ?? ?? ??
   at Anamnesis.Core.Memory.SignatureScanner.Scan(IntPtr baseAddress, Int32 size, String signature)
   at Anamnesis.Core.Memory.SignatureScanner.ScanText(String signature)
   at Anamnesis.Core.Memory.AddressService.<>c__DisplayClass99_0.<GetBaseAddressFromSignature>b__0()
2021-12-13 07:49:06.976 -05:00 [FTL] Failed to scan memory for base address from signature (Have you tried restarting FFXIV?)
System.Collections.Generic.KeyNotFoundException: Can't find a signature of 48 8B 15 ?? ?? ?? ?? 4C 8B 82 18 16 00 00
   at Anamnesis.Core.Memory.SignatureScanner.Scan(IntPtr baseAddress, Int32 size, String signature)
   at Anamnesis.Core.Memory.SignatureScanner.ScanText(String signature)
   at Anamnesis.Core.Memory.AddressService.<>c__DisplayClass99_0.<GetBaseAddressFromSignature>b__0()
2021-12-13 07:49:06.986 -05:00 [FTL] Failed to scan memory for text signature (Have you tried restarting FFXIV?)
System.Collections.Generic.KeyNotFoundException: Can't find a signature of 48 89 ?? 08 16 00 00 48 69
   at Anamnesis.Core.Memory.SignatureScanner.Scan(IntPtr baseAddress, Int32 size, String signature)
   at Anamnesis.Core.Memory.SignatureScanner.ScanText(String signature)
   at Anamnesis.Core.Memory.AddressService.<>c__DisplayClass98_0.<GetAddressFromTextSignature>b__0()

**Comment by damphands** [comment]
021-12-13 07:48:44.429 -05:00 [INF] Anamnesis Version: 7/26/2021 5:30:00 PM

This is an old version of Anamnesis. Please update by going to the released page.
