### ISSUE TITLE
[Critical error] Failed to initialize Lumina

### ISSUE THREAD

**Issue by YonahOhara** [imchillin/Anamnesis#806]
Hello,

Fresh install, tried with latest version of .Net Desktop Runtime as well as with the one linked in the files

```
2022-01-19 23:12:23.384 +01:00 [INF] OS: Microsoft Windows 10.0.19043
2022-01-19 23:12:23.384 +01:00 [INF] Framework: .NET 5.0.9
2022-01-19 23:12:23.385 +01:00 [INF] OS Architecture: X64
2022-01-19 23:12:23.385 +01:00 [INF] Process Architecture: X64
2022-01-19 23:12:23.385 +01:00 [INF] Anamnesis Version: 2022-01-06 01:51
2022-01-19 23:12:23.385 +01:00 [INF] Check Working Directory: "..."
2022-01-19 23:12:23.397 +01:00 [INF] Initialized service: LogService
2022-01-19 23:12:23.400 +01:00 [INF] Initialized service: SerializerService
2022-01-19 23:12:23.443 +01:00 [INF] Initialized service: SettingsService
2022-01-19 23:12:23.450 +01:00 [INF] Last update check was less than 6 hours ago. Skipping.
2022-01-19 23:12:23.450 +01:00 [INF] Initialized service: UpdateService
2022-01-19 23:12:23.459 +01:00 [INF] Initialized service: LocalizationService
2022-01-19 23:12:23.460 +01:00 [INF] Initialized service: ViewService
2022-01-19 23:12:23.506 +01:00 [INF] Found game version: 2021.12.24.0000.0000
2022-01-19 23:12:23.535 +01:00 [INF] Module base: 140701839986688
2022-01-19 23:12:23.535 +01:00 [INF] Module size: 24092210
2022-01-19 23:12:24.576 +01:00 [INF] Took 1040ms to scan for 22 addresses
2022-01-19 23:12:24.577 +01:00 [INF] Initialized service: MemoryService
2022-01-19 23:12:24.577 +01:00 [INF] Initialized service: AddressService
2022-01-19 23:12:24.578 +01:00 [INF] Initialized service: TargetService
2022-01-19 23:12:24.579 +01:00 [INF] Initialized service: FileService
2022-01-19 23:12:24.579 +01:00 [INF] Initialized service: TerritoryService
2022-01-19 23:12:24.579 +01:00 [INF] Initialized service: GameService
2022-01-19 23:12:24.579 +01:00 [INF] Initialized service: TimeService
2022-01-19 23:12:24.580 +01:00 [INF] Initialized service: CameraService
2022-01-19 23:12:24.580 +01:00 [INF] Initialized service: GposeService
2022-01-19 23:12:24.583 +01:00 [INF] Found game client region: Global
2022-01-19 23:12:24.930 +01:00 [FTL] GameDataService Error: Failed to initialize Lumina (Are your game files up to date?)
System.Exception: Failed to initialize Lumina (Are your game files up to date?)
 ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'length')
   at Lumina.Extensions.BinaryReaderExtensions.ReadStructure[T](BinaryReader br)
   at Lumina.Data.SqPackIndex.LoadIndex()
   at Lumina.Data.Repository.SetupIndexes()
   at Lumina.GameData..ctor(String dataPath, LuminaOptions options)
   at Anamnesis.Services.GameDataService.Initialize()
   --- End of inner exception stack trace ---
   at Anamnesis.Services.GameDataService.Initialize()
   at Anamnesis.Services.ServiceManager.Add[T]()
2022-01-19 23:13:23.373 +01:00 [INF] 369Mb memory In use.

```

**Comment by Ani-ki** [comment]
[**FAQ**](https://github.com/imchillin/Anamnesis/wiki/FAQ#i-opened-an-issue-or-feature-request-but-it-was-closed-what-happened)
