### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by YonahOhara** [imchillin/Anamnesis#807]
**Describe the bug**
The tool crashes on startup

**To Reproduce**
Steps to reproduce the behaviour:
1. Download the latest version from the repository
2. Install the .Net runtime linked in the files
3. Try to launch the tool
4. An error pops up and leaves no other choice but to terminate the program

**Expected behaviour**
The program launches

**Log file**
[2022-01-19-23-12-23.txt](https://github.com/imchillin/Anamnesis/files/7900935/2022-01-19-23-12-23.txt)

PS: sorry for my previous issue

**Comment by YonahOhara** [comment]
I have tried using the latest version of CMT and I appear to have the same problem, the issue may be solely on my end. I'll try reinstalling the game sometime.

Here is the error from CMT in case in could be of any use : 

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at ConceptMatrix.App.App_Exit(Object sender, ExitEventArgs e)
   at System.Windows.Application.OnExit(ExitEventArgs e)
   at System.Windows.Application.DoShutdown()
   at System.Windows.Application.ShutdownImpl()
   at System.Windows.Application.ShutdownCallback(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by Yuki-Walsh** [comment]
yea, looks like it might be corrupt game files. Mods might cause that if something has gone wrong.
